<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenTestingWithCSVFile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>011387ad-5748-4310-b079-a12f6541c860</testSuiteGuid>
   <testCaseLink>
      <guid>33bc8015-36c7-4a77-bd23-aeb0f02f61f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AirbnbDemo/Find a place</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c66d4062-9b0a-4b66-a903-72ed06ed3345</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/100_Cities_CSV</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>c66d4062-9b0a-4b66-a903-72ed06ed3345</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value></value>
         <variableId>fbc71c88-1a87-4b2c-a89c-edbee831612a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c66d4062-9b0a-4b66-a903-72ed06ed3345</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value></value>
         <variableId>5a5aa52e-b2d1-4174-9afa-1c896892f3e4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
