<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Where_query</name>
   <tag></tag>
   <elementGuidId>8810dd3e-aeb1-40ad-940f-c475a0b9c081</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bigsearch-query-location-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bigsearch-query-location-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;structured-search-input-field-query&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3b8cb8c-1db2-43bd-9403-dcd46f7c1216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fp9kp52 atm_9s_1ulexfb atm_3f_idpfg4 atm_gi_idpfg4 atm_l8_idpfg4 atm_vy_1osqo2v atm_26_glywfm atm_c8_86zae atm_g3_1s00pb0 atm_fr_1h5ikn atm_cs_10d11i2 atm_7l_dezgoh atm_sq_1l2sidv atm_vv_1q9ccgz atm_ks_zryt35 atm_c8_86zae_17x46du atm_g3_1s00pb0_17x46du atm_fr_1h5ikn_17x46du atm_cs_6adqpa_17x46du atm_7l_1esdqks_17x46du atm_c8_86zae_y5ttn9 atm_g3_1s00pb0_y5ttn9 atm_fr_1h5ikn_y5ttn9 atm_cs_6adqpa_y5ttn9 atm_7l_1esdqks_y5ttn9 atm_c8_86zae_1k1obal atm_g3_1s00pb0_1k1obal atm_fr_1h5ikn_1k1obal atm_cs_6adqpa_1k1obal atm_7l_1esdqks_1k1obal atm_c8_86zae_m14rgb atm_g3_1s00pb0_m14rgb atm_fr_1h5ikn_m14rgb atm_cs_6adqpa_m14rgb atm_7l_1esdqks_m14rgb atm_c8_86zae_3ykvna atm_g3_1s00pb0_3ykvna atm_fr_1h5ikn_3ykvna atm_cs_6adqpa_3ykvna atm_7l_1esdqks_3ykvna atm_9s_glywfm_169oxbr atm_9s_glywfm_10uishg atm_9s_glywfm_136h51u atm_kd_glywfm_pfnrn2 atm_ll_1fwxnve_c2x6ez dir dir-ltr</value>
      <webElementGuid>c8479bf6-076c-45a5-9b1a-cb39dc0068c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>ba59efe5-7ec8-466a-b889-21138bc17404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>df13eebe-69be-4755-bc96-75a1e520a8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bigsearch-query-location-description</value>
      <webElementGuid>82ac9d01-43c7-4051-ad38-858f5c3c985a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>structured-search-input-field-query</value>
      <webElementGuid>ca0d051e-315e-4476-890f-f0af6331ad51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>2864b2e7-de28-4c3d-936a-96408d88fb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>62cbefd1-03de-47a1-a4c7-8043a70a5093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8fbaaf02-ab4e-4100-956e-11e3708c984d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>475f8982-3042-42f5-965c-1be5d0f0a1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bigsearch-query-location-input</value>
      <webElementGuid>3fd629df-410c-45d3-be13-d09395944843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>query</value>
      <webElementGuid>2bde427f-0aa1-433c-ba9f-32398891f6ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6b6a9df8-b90f-4262-a7ef-05f6a48aa258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>bigsearch-query-location-listbox</value>
      <webElementGuid>7a156eb3-258d-447c-bfe5-d3c0bbe8ed9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c0e14354-480f-4bf4-98d1-cfcd2955a959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>88e94987-9ecd-4d79-873f-340443655539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>f8fab177-8619-4c18-85f5-6c944c1d69b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigsearch-query-location-input&quot;)</value>
      <webElementGuid>458e6c31-131e-467b-86e7-88f41227357f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bigsearch-query-location-input']</value>
      <webElementGuid>08035dee-b291-46a8-a90e-0fef029887da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-application']/div/div/div/div/div/div[2]/div/div/div/header/form/div/div/div[2]/div[2]/div/div[2]/div[2]/input</value>
      <webElementGuid>3cc9678d-359c-41f9-a692-da4c3cc3d56a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a10cc738-b1d3-4ecc-ab7f-90b79d182bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'a' and @id = 'bigsearch-query-location-input' and @name = 'query']</value>
      <webElementGuid>d6241c9d-f302-493e-bf31-bb9859f1daa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
